### PR TITLE
:lipstick: Code styling

### PR DESCRIPTION
**Pull request by philipgiuliani**
Javascript variables must be lowercased, only Objects should be capitalized.

### CODE REVIEW

**Comment by steelbrain** [comment]
Well, I write javascript variables in Uppercase, It makes them readable IMHO. and I was gonna write a case where it would duplicate the other line so left a note of `# Ignore it for once`

**Comment by steelbrain** [comment]
I am happy to merge this if you implement the duplicate current line part of it.

**Comment by philipgiuliani** [comment]
Thanks for your answer :) Ok i saw it now in your other projects.
You dont have fear to overwrite class names? I saw that you have overwritten the `Error` class for example (in another project), which is a default JS function.. But everybody has its style, and thats good! :)

Ok now i understand why you left the comment there.. I think i could try that part if you want!

**Comment by steelbrain** [comment]
That would be awesome :+1:

**Comment by philipgiuliani** [comment]
Done, i  dont know if i have time today to play around with it, but ill try it!

**Comment by steelbrain** [comment]
Great!

**Pull request closed without merging**
